// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project_Work_My_Telegram_bot;

#nullable disable

namespace Project_Work_My_Telegram_bot.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.CarDrive", b =>
                {
                    b.Property<long>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CarId"));

                    b.Property<string>("CarName")
                        .HasColumnType("text");

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GasСonsum")
                        .HasColumnType("double precision");

                    b.Property<int>("TypeFuel")
                        .HasColumnType("integer");

                    b.Property<bool>("isPersonalCar")
                        .HasColumnType("boolean");

                    b.HasKey("CarId");

                    b.HasAlternateKey("CarNumber");

                    b.ToTable("CarDrive");
                });

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.ObjectPath", b =>
                {
                    b.Property<int>("IdPath")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPath"));

                    b.Property<long?>("CarDriveCarId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CarId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DatePath")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PathLengh")
                        .HasColumnType("real");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("IdPath");

                    b.HasIndex("CarDriveCarId");

                    b.HasIndex("UserId");

                    b.ToTable("ObjectPath");
                });

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.OtherExpenses", b =>
                {
                    b.Property<int>("ExpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpId"));

                    b.Property<decimal>("Coast")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateTimeExp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameExpense")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ExpId");

                    b.HasIndex("UserId");

                    b.ToTable("OtherExpense");
                });

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.User", b =>
                {
                    b.Property<long>("IdTg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTg"));

                    b.Property<string>("JobTitlel")
                        .HasColumnType("text");

                    b.Property<string>("TgUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("UserRol")
                        .HasColumnType("integer");

                    b.Property<long?>("РersonalcarCarId")
                        .HasColumnType("bigint");

                    b.HasKey("IdTg");

                    b.HasIndex("РersonalcarCarId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.ObjectPath", b =>
                {
                    b.HasOne("Project_Work_My_Telegram_bot.ClassDB.CarDrive", "CarDrive")
                        .WithMany()
                        .HasForeignKey("CarDriveCarId");

                    b.HasOne("Project_Work_My_Telegram_bot.ClassDB.User", "UserPath")
                        .WithMany("ObjectPath")
                        .HasForeignKey("UserId");

                    b.Navigation("CarDrive");

                    b.Navigation("UserPath");
                });

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.OtherExpenses", b =>
                {
                    b.HasOne("Project_Work_My_Telegram_bot.ClassDB.User", "UserExp")
                        .WithMany("OtherExpenses")
                        .HasForeignKey("UserId");

                    b.Navigation("UserExp");
                });

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.User", b =>
                {
                    b.HasOne("Project_Work_My_Telegram_bot.ClassDB.CarDrive", "Рersonalcar")
                        .WithMany("User")
                        .HasForeignKey("РersonalcarCarId");

                    b.Navigation("Рersonalcar");
                });

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.CarDrive", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_Work_My_Telegram_bot.ClassDB.User", b =>
                {
                    b.Navigation("ObjectPath");

                    b.Navigation("OtherExpenses");
                });
#pragma warning restore 612, 618
        }
    }
}
